stages:
  - dependencies

angular_dependencies:
  image: node:12-alpine
  stage: dependencies
  script:
    - cd client
    - npm install
  only:
    - main
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

flask_dependencies:
  stage: dependencies
  script: 
    - cd server 
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python src/app.py
