stages:
  - dependencies
  - test 
  - build

angular_dependencies:
  image: node:12-alpine
  stage: dependencies
  script:
    - cd client
    - npm install
  only:
    - main
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

angular_build:
  image: node:12-alpine
  stage: build
  script:
    - cd client
    - npm link @angular/cli@11.2.6
    - npm run build
  only:
    - main
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull
