CREATE TABLE `pcde_metrics_seq_cumul` (
	`fixn_id` INT(11) NOT NULL COMMENT 'foreign key from pcde_fixations',
	`DOCID_USERID` VARCHAR(200) NOT NULL COMMENT 'concat(docid, \'_\', userid) ==> for easy searching of doc_usr pair, for display purposes ' COLLATE 'utf8_general_ci',
	`fixn_n` INT(11) NOT NULL COMMENT 'cumulative # fixations (running fixn count) (also seq no of this row for this DOCID_USERID)',
	`p_rlvnc` TINYINT(4) NOT NULL COMMENT 'perceived relevance: 0 = Irrelevant; 1 = Relevant',
	`t_rlvnc` TINYINT(4) NOT NULL COMMENT 'true (by-design) relevance: 0 = Irrelevant; 1 = Relevant; 2 = Topical',
	`fixn_st_rel` DOUBLE NULL DEFAULT NULL COMMENT 'time of fixation start, relative to task start time (seconds) (a.k.a. actual time)',
	`fixn_end_rel` DOUBLE NULL DEFAULT NULL COMMENT 'time of fixation end, relative to task start time (seconds) (a.k.a. actual time) (time elapsed in task)',
	`fixn_end_rel_delta` DOUBLE NULL DEFAULT NULL COMMENT '>>> diff between current fixn_end and prev fixn_end',
	`fixn_st_fraction` DOUBLE NULL DEFAULT NULL COMMENT 'time of fixation start, as proportion of task duration: fixn_st_rel / task_dur (between 0 and 1) (for plotting) (a.k.a. relative time)',
	`fixn_end_fraction` DOUBLE NULL DEFAULT NULL COMMENT 'time of fixation end, as proportion of task duration (between 0 and 1) (for plotting) (a.k.a. relative time)',
	`fixn_dur_fraction` DOUBLE NULL DEFAULT NULL COMMENT 'fixation duration, as proportion of task duration',
	`fixn_n_fraction` DOUBLE NOT NULL COMMENT 'cumul fixn_n / total fixn_n : fraction of fixations covered so far (betn 0 and 1) (for plotting)',
	`fixn_n_l1` INT(11) NOT NULL COMMENT 'cumulative # fixations in Level 1: 110 - 249 ms',
	`fixn_n_l2` INT(11) NOT NULL COMMENT 'cumulative # fixations in Level 2: 250 - 399 ms',
	`fixn_n_l3` INT(11) NOT NULL COMMENT 'cumulative # fixations in Level 3: 400 - 549 ms',
	`fixn_n_l4` INT(11) NOT NULL COMMENT 'cumulative # fixations in Level 4: >=550 ms',
	`fixn_rate` DOUBLE NULL DEFAULT NULL COMMENT 'cumulative # fixations per unit time (seconds) = (cumul) fixn_n / fixn_end_rel (n / seconds)',
	`fixn_dur_sum` DOUBLE NULL DEFAULT NULL COMMENT 'cumul sum (all fixation durations) (ms)',
	`fixn_dur_avg` DOUBLE NULL DEFAULT NULL COMMENT 'cumul avg (all fixation durations) (ms)',
	`fixn_dur_sd` DOUBLE NULL DEFAULT NULL COMMENT 'cumul sd (all fixation durations) (ms)',
	`fixn_hull_2d_area` DOUBLE NULL DEFAULT NULL COMMENT 'cumul area of the convex hull of fixn points, normalized by stimulus area',
	`fixn_hull_2d_area_delta` DOUBLE NULL DEFAULT NULL COMMENT '>>> diff between fixn_hull_2d_area of current fixn and prev fixn',
	`fixn_hull_2d_area_per_time` DOUBLE NULL DEFAULT NULL COMMENT '>>> = fixn_hull_2d_area / fixn_end_rel',
	`fixn_hull_2d_area_delta_per_delta_time` DOUBLE NULL DEFAULT NULL COMMENT '>>> = fixn_hull_2d_area_delta / fixn_end_rel_delta',
	`fixn_hull_3d_s_area` DOUBLE NULL DEFAULT NULL COMMENT 'cumul surface area of the 3D convex hull of 3D fixn points (x, y, t_end), normalized by stimulus area',
	`fixn_hull_3d_vol` DOUBLE NULL DEFAULT NULL COMMENT 'cumul volume of the 3D convex hull of 3D fixn points (x, y, t_end), normalized by stimulus area',
	`fixn_hull_2d_x` DOUBLE NULL DEFAULT NULL COMMENT 'cumul x-coordinate of the centroid of convex hull',
	`fixn_hull_2d_y` DOUBLE NULL DEFAULT NULL COMMENT 'cumul y-coordinate of the centroid of convex hull',
	`fixn_hull_3d_x` DOUBLE NULL DEFAULT NULL COMMENT 'cumul t-coordinate of the centroid of 3D convex hull',
	`fixn_hull_3d_y` DOUBLE NULL DEFAULT NULL,
	`fixn_hull_3d_t` DOUBLE NULL DEFAULT NULL,
	`fixns_per_unit_hull_2d_area` DOUBLE NULL DEFAULT NULL COMMENT 'cumul fixn_n / fixn_hull_2d_area',
	`fixns_per_unit_hull_2d_area_delta` DOUBLE NULL DEFAULT NULL COMMENT '>>> diff betwn value of curr fixn and prev fixn',
	`fixns_per_unit_hull_2d_area_per_time` DOUBLE NULL DEFAULT NULL COMMENT '>>> = fixns_per_unit_hull_2d_area / fixn_end_rel',
	`fixns_per_unit_hull_2d_area_delta_per_delta_time` DOUBLE NULL DEFAULT NULL COMMENT '>>> = fixns_per_unit_hull_2d_area_delta / fixn_end_rel_delta',
	`fixns_per_unit_hull_3d_vol` DOUBLE NULL DEFAULT NULL COMMENT 'cumul fixn_n / fixn_hull_3d_vol',
	`fixns_per_unit_hull_3d_s_area` DOUBLE NULL DEFAULT NULL COMMENT 'cumul fixn_n / fixn_hull_3d_s_area',
	`scan_dist_euclid` DOUBLE NULL DEFAULT NULL COMMENT 'cumul total euclidean distance scanned (px), normalized by stimuls area',
	`scan_dist_3d_euclid` DOUBLE NULL DEFAULT NULL COMMENT 'cumul total 3D euclidean distance scanned (px), normalized by stimuls area',
	`scan_dist_h` DOUBLE NULL DEFAULT NULL COMMENT 'cumul horizontal distance scanned (px), normalized by stimulus width',
	`scan_dist_v` DOUBLE NULL DEFAULT NULL COMMENT 'cumul vertical distance scanned (px), normalized by stimulus width',
	`scan_hv_ratio` DOUBLE NULL DEFAULT NULL COMMENT 'cumul scan_dist_h / scan_dist_v (co-tangent or cot theta) (>1 for predominantly horizontal movement; <1 for vertical) (auto normalized by stimulus dimensions)',
	`scan_hv_ratio_delta` DOUBLE NULL DEFAULT NULL COMMENT '>>> diff between cur fixn and prev fixn',
	`scan_hv_ratio_per_time` DOUBLE NULL DEFAULT NULL COMMENT '>>> = scan_hv_ratio / fixn_end_rel',
	`scan_hv_ratio_delta_per_delta_time` DOUBLE NULL DEFAULT NULL COMMENT '>>> = scan_hv_ratio_delta / fixn_end_rel_delta',
	`scan_speed` DOUBLE NULL DEFAULT NULL COMMENT 'cumul scanning speed = scan_dist_euclid / fixn_end_rel (px/s) (normalized by screen dim)',
	`scan_speed_h` DOUBLE NULL DEFAULT NULL COMMENT 'cumul horizontal scanning speed = scan_dist_h / fixn_end_rel (px/s) (normalized by screen dim)',
	`scan_speed_v` DOUBLE NULL DEFAULT NULL COMMENT 'cumul vertical scanning speed = scan_dist_v / fixn_end_rel (px/s) (normalized by screen dim)',
	`fixn_per_scan_dist` DOUBLE NULL DEFAULT NULL COMMENT 'cumul avg # fixations per unit scan distance = fixn_ct / scan_dist_euclid',
	`fixn_per_scan_dist_3d` DOUBLE NULL DEFAULT NULL COMMENT 'cumul avg # fixations per unit scan distance = fixn_ct / scan_dist_3d_euclid',
	`avg_sacc_len` DOUBLE NULL DEFAULT NULL COMMENT 'cumul avg (length of saccade) (px)',
	`avg_sacc_len_3d` DOUBLE NULL DEFAULT NULL COMMENT 'cumul avg (length of 3D saccade) (px)',
	`z_fixn_dur` DOUBLE NULL DEFAULT NULL,
	`z_sacc_len` DOUBLE NULL DEFAULT NULL,
	`coeff_K_i` DOUBLE NULL DEFAULT NULL,
	`box_area` DOUBLE NULL DEFAULT NULL COMMENT 'cumul scan_dist_h * scan_dist_v  (ETWEB\'20 rebuttal)',
	`box_area_per_time` DOUBLE NULL DEFAULT NULL COMMENT 'running_box_area / time_elapsed_in_task  (ETWEB\'20 rebuttal)',
	`fixns_per_box_area` DOUBLE NULL DEFAULT NULL COMMENT 'running_fixation_count / running box_area  (ETWEB\'20 rebuttal)',
	PRIMARY KEY (`DOCID_USERID`, `fixn_n`) USING BTREE,
	INDEX `FK_pcde_metrics_sequence_cumulative_pcde_fixations` (`fixn_id`) USING BTREE,
	INDEX `p_rlvnc` (`p_rlvnc`) USING BTREE,
	INDEX `t_rlvnc` (`t_rlvnc`) USING BTREE,
	CONSTRAINT `FK_pcde_metrics_sequence_cumulative_pcde_fixations` FOREIGN KEY (`fixn_id`) REFERENCES `sandbox`.`pcde_fixations` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
)
COMMENT='cumulative values of different metrics in sequential fashion, for each fixation in pcde_fixations. IS_FIXN_CROSSHAIR = 0\r\nFor sequence computations in ETRA\'20 paper\r\n- all delta measure times are in seconds\r\n- fixn_per_scan_dist and avg_sacc_len are (almost) reciprocals\r\n- 3D measures are NOT normalized by total task time (since it will be unknown in real-time systems)\r\n\r\n'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPACT
;
